/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Grade extends javax.swing.JFrame {

    /**
     * Creates new form Grade
     */
    public Grade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Rio de Janeiro", "87"},
                {"São Paulo", "356"},
                {"Minas Gerais", "56"}
            },
            new String [] {
                "Cidades", "Municipios"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 230, 260);

        jButton1.setText("Informações");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 220, 150, 23);

        jButton2.setText("Dados da Tabela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 60, 150, 23);

        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 140, 150, 23);

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(270, 180, 150, 23);

        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(270, 100, 150, 23);

        jButton6.setText("Criar tabela");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(270, 20, 150, 23);

        jButton7.setText("Item selecionado");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(270, 260, 150, 23);

        setBounds(0, 0, 470, 335);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String infos = "";
        infos += "Quant. linhas: " + jTable1.getModel().getRowCount() + "\n";
        infos += "Quant. colunas: " + jTable1.getModel().getColumnCount() + "\n";
        infos += "Linha selecionada: " + jTable1.getSelectedRow() + "\n";
        infos += "Coluna selecionada: " + jTable1.getSelectedColumn() + "\n";
        if (jTable1.getModel().getRowCount()>0) {
              infos += "Cabeçalhos das colunas: " + jTable1.getColumnName(0)+ ", " + 
                             jTable1.getColumnName(1) + "\n";
        }
        JOptionPane.showMessageDialog(null, infos, "Informações", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String dados = "";
        for (int i=0; i< jTable1.getModel().getRowCount(); i++ ){
            dados += "Linha " + i + ": ";
            for (int j=0; j< jTable1.getModel().getColumnCount(); j++ ) { 
                dados += "  " + jTable1.getModel().getValueAt(i,j); //método da classe TableModel
            }
            dados += "\n";
        }
        JOptionPane.showMessageDialog(null, dados, "Dados da tabela", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getModel().getRowCount()>=2 && jTable1.getModel().getColumnCount()>=2 ) {
           jTable1.getModel().setValueAt("Cidade qualquer",1,0);
           jTable1.setValueAt("Número qualquer", 1, 1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       int linhaSelecionada = jTable1.getSelectedRow() ;
       if (linhaSelecionada != -1) {
           ((DefaultTableModel)jTable1.getModel()).removeRow(linhaSelecionada);
       }
       else {
                JOptionPane.showMessageDialog(null, 
                                "Por favor, selecione a linha a ser eliminada.", 
                                "Eliminação",
                                JOptionPane.INFORMATION_MESSAGE);
       }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // Para adicionar uma linha vazia, podemos executar:
        // int numAtualLinhas = ((DefaultTableModel)jTable1.getModel()).getRowCount();
        // ((DefaultTableModel)jTable1.getModel()).setNumRows(numAtualLinhas + 1);
        Object dados [] = new Object[2];
        dados[0] = "Cidade 1"; // ou poderia pegar o valor de um jTextField1.getText();
        dados[1] = "222"; // ou poderia pegar o valor de um jTextField2.getText();
        ((DefaultTableModel)jTable1.getModel()).addRow(dados);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String titulos[] = {"Identificação", "Nome"};
        Object dados[][] = {{1, "Sócrates"},
                            {2, "Platão"},
                            {3, "Aristóteles"},
                            {4, "Kant"},
                            {5, "Descartes"}};


        DefaultTableModel modelo = new DefaultTableModel(dados, titulos);
        jTable1.setModel(modelo);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Nada selecionado");
        } else {
            //int it = jTable1.getSelectionModel().getMinSelectionIndex();
            int it = jTable1.getSelectedRow();
            String escolhido = jTable1.getModel().getValueAt(it, 0) + ", " + jTable1.getModel().getValueAt(it, 1);
            JOptionPane.showMessageDialog(null, escolhido);
        }        

    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
