import java.util.Locale;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alcides
 */
public class Imobiliaria extends javax.swing.JInternalFrame {

    /**
     * Creates new form Imobiliaria
     */
    public Imobiliaria() {
        initComponents();
        jList2.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 255, 204));
        setClosable(true);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Valor do/s apartamento/s: R$ ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 270, 390, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 210, 120, 40);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 150, 30, 30);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setText("Qtde. unidades a comprar: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 130, 160, 14);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o tipo de pagamento"));
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel2.setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Pagamento à vista");
        jRadioButton1.setOpaque(false);
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(20, 30, 160, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Pagamento parcelado");
        jRadioButton2.setOpaque(false);
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(20, 60, 160, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(200, 20, 190, 100);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione o andar desejado"));
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel3.setLayout(null);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 30, 130, 120);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 20, 170, 170);

        setBounds(0, 0, 421, 346);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Botao calcular
        int quantAptos=0, andar=0;
        String tipoPgto="";
        float valor=0.0f;

        //para formatar milhares e casas decimais:
        Locale loc = getLocale(); //importar java.util.Locale
        java.text.NumberFormat nf = java.text.NumberFormat.getNumberInstance(loc);
        java.text.DecimalFormat df = (java.text.DecimalFormat)nf;
        df.applyPattern("###,###.00");

        //vejamos se é pagamento à vista ou parcelado:
        if(jRadioButton1.isSelected()) tipoPgto="avista"; else tipoPgto="parcelado";
        //confiando que na lista só tem números inteiros?
        andar = Integer.parseInt(jList2.getSelectedValue().toString());
        //quantidade de apartamentos a comprar:
        quantAptos = Integer.parseInt(jTextField1.getText());

        switch(andar) {
            case 1:
            valor = 100000.0f;
            break;
            case 2:
            valor = 120000.0f;
            break;
            case 3:
            case 4:
            valor = 205000.0f;
            break;
            case 5:
            case 6:
            case 7:
            case 8:
            case 9:
            valor = 215000.0f;
            break;
            case 10:
            case 11:
            case 12:
            valor = 245000.0f;
            break;
            case 13:
            case 14:
            valor = 445000.0f;
            break;
        }

        /*  ou desta outra forma:
        if(andar==1) valor=100000.0f;
        if(andar==2) valor=120000.0f;
        if(andar==3 || andar==4) valor=205000.0f;
        if(andar>=5 && andar<=9) valor=215000.0f;
        if(andar>=10 && andar<=12) valor=245000.0f;
        if(andar==13 || andar==14) valor=445000.0f;
        */

        valor = valor * quantAptos;
        if(andar <=6 && tipoPgto.equalsIgnoreCase("avista")) {
            valor = valor * 0.9f;
        }
        jLabel3.setText("Valor do/s apartamento/s: R$ " + df.format(valor));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        //valor da entrada, só permitimos números, qualquer outro caractere será cancelado:
        if( (evt.getKeyChar()<'0' || evt.getKeyChar()>'9') ) evt.setKeyChar((char)27);
    }//GEN-LAST:event_jTextField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
