
public class Provedor extends javax.swing.JInternalFrame {

    /** Creates new form JamelaProv */
    public Provedor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Provedor de Internet");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selecione a Cidade"));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jList1.setBackground(new java.awt.Color(204, 204, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Americanas", "Belo Horizonte", "Campinas", "Campo Grande", "Mariporã", "Pouso Alegre", "Rio de Janeiro", "São Bernardo", "São José dos Campos", "São Paulo", "Taubaté" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(16, 27, 169, 149);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 200, 190);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selecione a Cidade"));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("1 Mbps");
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(12, 32, 80, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2 Mpbs");
        jRadioButton2.setOpaque(false);
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(12, 58, 80, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 10, 120, 107);

        jCheckBox1.setText("Ponto Adicional");
        jCheckBox1.setOpaque(false);
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(350, 30, 110, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 70, 97, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Valor da Mensalidade: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 150, 250, 15);

        setBounds(0, 0, 482, 255);
    }// </editor-fold>//GEN-END:initComponents
    private void mensalidade(){
        float men;
        
        if (jList1.getSelectedIndex()==-1) {
            jLabel1.setText("Por favor, selecione a cidade!");
            return;
        }
                
        if (jList1.getSelectedValue().equals("Rio de Janeiro") 
                || jList1.getSelectedValue().equals("São Paulo") 
                || jList1.getSelectedValue().equals("Belo Horizonte")) {
            //para Rio, SP e BH:
            if(jRadioButton1.isSelected())men = 82.90f; else men = 98.00f;
        }
        else  {
            //para as restantes cidades:
            if(jRadioButton1.isSelected())men = 101.30f; else men = 124.50f;
        }
        
        if (jCheckBox1.isSelected()) {
            //para qualquer cidade, pelo ponto adicional: + R$50,00
            men = men + 50;
        }
        jLabel1.setText("Valor da Mensalidade: R$" + men);
    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mensalidade();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
