
package view;

import dao.Paciente;
import dao.PacienteDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;


public class Formulario extends javax.swing.JFrame {

    /** Creates new form */
    public Formulario() {
        initComponents();
        carregarLista();
    }

    
    public DefaultFormatterFactory setFormatoData() {             
        try {
            return new DefaultFormatterFactory(new MaskFormatter("##/##/####")); 
        } catch (Exception pe) {}
        return null;
    }

    public void carregarLista() {
        //Captura o modelo que preenche a tabela
        DefaultTableModel modelo = (DefaultTableModel) tabela01.getModel();        
        ArrayList<Paciente> lista = new PacienteDAO().listaPacientes();
        modelo.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{ lista.get(i).getCodigo()+"", 
                                        lista.get(i).getPaciente(),
                                        lista.get(i).getNascimento(),
                                        lista.get(i).getSexo()
                                        }
                          );
        }  
        //configura o codigo com o número do prox registro
        codigo.setText(new PacienteDAO().getLastCodigo()+"");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela01 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nascimento = new javax.swing.JFormattedTextField();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Médica UNICSUL");
        getContentPane().setLayout(null);

        tabela01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Paciente", "Nascimento", "Sexo"
            }
        ));
        jScrollPane1.setViewportView(tabela01);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 200, 560, 160);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Pacientes"));
        jPanel1.setLayout(null);

        jLabel1.setText("Nascimento:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(16, 96, 80, 14);

        nascimento.setColumns(8);
        nascimento.setFormatterFactory(setFormatoData());
        jPanel1.add(nascimento);
        nascimento.setBounds(100, 93, 110, 20);
        jPanel1.add(nome);
        nome.setBounds(100, 63, 444, 20);

        jLabel2.setText("Paciente:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(16, 63, 66, 14);

        codigo.setEnabled(false);
        jPanel1.add(codigo);
        codigo.setBounds(100, 27, 88, 20);

        jLabel3.setText("Código:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(16, 30, 66, 14);

        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(16, 132, 34, 14);

        sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jPanel1.add(sexo);
        sexo.setBounds(100, 129, 110, 20);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 140, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 560, 170);

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 370, 90, 23);

        setSize(new java.awt.Dimension(628, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Paciente p = montaPaciente();
        String resp = new PacienteDAO().gravarPaciente(p);        
        if(resp.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Paciente Gravado com sucesso");
            limparCampos();
            carregarLista();
        }
        else {
            JOptionPane.showMessageDialog(null, "Erro ao gravar.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (tabela01.getSelectedRow() <0){
            JOptionPane.showMessageDialog(null, "Selecione um registro.");
        }
        else
        {
            if (new PacienteDAO().delPaciente(Integer.parseInt(
                                                        tabela01.getModel().getValueAt(
                                                            tabela01.getSelectedRow(), 0).toString()))){            
                JOptionPane.showMessageDialog(null, "Registro excluído.");
                limparCampos();
                carregarLista();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Registro não encontrado.");
            }
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    public Paciente montaPaciente(){
        Paciente p = new Paciente();
        p.setPaciente(nome.getText());
        p.setNascimento(nascimento.getText());
        p.setSexo(sexo.getSelectedItem().toString());        
        return p;
    }   
    
    public void limparCampos(){
        nome.setText("");
        nascimento.setText("");
        sexo.setSelectedIndex(0);        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField nascimento;
    private javax.swing.JTextField nome;
    private javax.swing.JComboBox sexo;
    private javax.swing.JTable tabela01;
    // End of variables declaration//GEN-END:variables
}
