package view;

import dao.Contato;
import dao.AgendaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.*;

public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();        
        carregarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setText("ID: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 18, 14);

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 34, 14);

        jLabel3.setText("Telefone:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 46, 14);

        jTextField1.setEditable(false);
        jTextField1.setFocusable(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 10, 50, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(80, 40, 290, 20);

        jFormattedTextField1.setFormatterFactory(setFormatoTel());
        jPanel1.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(80, 70, 140, 20);

        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(240, 70, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 380, 100);

        jButton1.setText("Incluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 270, 73, 23);

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 270, 73, 23);

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 270, 73, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 380, 130);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Contato c = montaContato();
        String resp = new AgendaDAO().gravarContato(c);        
        if(resp.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Contato Gravado com sucesso");
            limparCampos();
            carregarLista();
        }
        else {
            JOptionPane.showMessageDialog(null, "Erro ao gravar.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jButton4.setVisible(true);
        int it = jTable1.getSelectedRow();
        jTextField1.setText(jTable1.getModel().getValueAt(it, 0).toString());
        jTextField2.setText(jTable1.getModel().getValueAt(it, 1).toString());
        jFormattedTextField1.setText(jTable1.getModel().getValueAt(it, 2).toString()); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        limparCampos();
        carregarLista();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if (jTable1.getSelectedRow() <0){
            JOptionPane.showMessageDialog(null, "Selecione um registro.");
        }
        else{
            if (new AgendaDAO().delContato(Integer.parseInt(
                                                        jTable1.getModel().getValueAt(
                                                            jTable1.getSelectedRow(), 0).toString()))){            
                JOptionPane.showMessageDialog(null, "Registro excluído.");
                limparCampos();
                carregarLista();
            }
            else{
                JOptionPane.showMessageDialog(null, "Registro não encontrado.");
            }
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Contato c = montaContato();
        String resp = new AgendaDAO().alterarContato(c);        
        if(resp.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Contato alterado com sucesso");
            limparCampos();
            carregarLista();
        }
        else {
            JOptionPane.showMessageDialog(null, "Erro ao gravar.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }
    
    public void carregarLista() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();        
        List<Contato> lista = new AgendaDAO().listarContatos();
        modelo.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new String[]{ lista.get(i).getId()+"",
                                        lista.get(i).getNome(), 
                                        lista.get(i).getTelefone()});
        }  
        jTextField1.setText(new AgendaDAO().getLastCodigo()+"");
        
        jButton4.setVisible(false);
    }
    
    public DefaultFormatterFactory setFormatoTel() {             
        try {
            return new DefaultFormatterFactory(new MaskFormatter("(##) ####-####")); 
        } catch (Exception e) {}
        return null;
    }

    public Contato montaContato(){
        Contato c = new Contato();
        c.setId(Integer.parseInt(jTextField1.getText()));
        c.setNome(jTextField2.getText());
        c.setTelefone(jFormattedTextField1.getText());        
        return c;
    }   
    
    public void limparCampos(){
        jTextField1.setText("");
        jTextField2.setText("");
        jFormattedTextField1.setText("");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
