
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * RGM: 1212121
 * NOME: Fulano da Silva
 * Curso: TADS
 */
public class LojaInfo extends javax.swing.JFrame {

    /**
     * Creates new form LojaInfo
     */
    public LojaInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        modHP = new javax.swing.JRadioButton();
        modDELL = new javax.swing.JRadioButton();
        modASUS = new javax.swing.JRadioButton();
        modSAMSUNG = new javax.swing.JRadioButton();
        acMOUSE = new javax.swing.JCheckBox();
        acIMP = new javax.swing.JCheckBox();
        acMONITOR = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        regiao = new javax.swing.JList();
        cartao = new javax.swing.JRadioButton();
        boleto = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados do cliente"));
        jPanel1.setLayout(null);

        jLabel1.setText("Nome do cliente:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 100, 14);

        jLabel2.setText("Sexo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 44, 50, 14);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Masculino");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(130, 40, 71, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Feminino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(40, 40, 93, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(90, 15, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 230, 70);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Loja de Informática");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 20, 440, 26);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Selecione o produto/acessórios"));
        jPanel2.setLayout(null);

        buttonGroup3.add(modHP);
        modHP.setText("HP");
        modHP.setOpaque(false);
        modHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modHPActionPerformed(evt);
            }
        });
        jPanel2.add(modHP);
        modHP.setBounds(10, 20, 39, 23);

        buttonGroup3.add(modDELL);
        modDELL.setText("Dell");
        modDELL.setOpaque(false);
        modDELL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modDELLActionPerformed(evt);
            }
        });
        jPanel2.add(modDELL);
        modDELL.setBounds(10, 40, 43, 23);

        buttonGroup3.add(modASUS);
        modASUS.setText("ASUS");
        modASUS.setOpaque(false);
        modASUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modASUSActionPerformed(evt);
            }
        });
        jPanel2.add(modASUS);
        modASUS.setBounds(10, 60, 51, 23);

        buttonGroup3.add(modSAMSUNG);
        modSAMSUNG.setText("Samsung");
        modSAMSUNG.setOpaque(false);
        modSAMSUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modSAMSUNGActionPerformed(evt);
            }
        });
        jPanel2.add(modSAMSUNG);
        modSAMSUNG.setBounds(10, 80, 69, 23);

        acMOUSE.setText("Mouse");
        jPanel2.add(acMOUSE);
        acMOUSE.setBounds(130, 20, 57, 23);

        acIMP.setText("Impressora");
        jPanel2.add(acIMP);
        acIMP.setBounds(130, 40, 79, 23);

        acMONITOR.setText("Monitor");
        jPanel2.add(acMONITOR);
        acMONITOR.setBounds(130, 60, 61, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 140, 230, 110);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Imagem do produto"));
        jPanel3.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel5);
        jLabel5.setBounds(15, 27, 150, 150);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(250, 60, 180, 190);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Local de entrega e dados de pagamento"));
        jPanel4.setLayout(null);

        jLabel4.setText("Região:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 40, 70, 14);

        regiao.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Região Norte", "Região Nordeste", "Região Centro-oeste", "Região Sudeste", "Região Sul" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        regiao.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(regiao);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(50, 30, 130, 35);

        buttonGroup2.add(cartao);
        cartao.setText("Cartão");
        cartao.setOpaque(false);
        jPanel4.add(cartao);
        cartao.setBounds(310, 40, 59, 23);

        buttonGroup2.add(boleto);
        boleto.setText("Boleto");
        boleto.setOpaque(false);
        jPanel4.add(boleto);
        boleto.setBounds(250, 40, 93, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 260, 420, 90);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Relatório do pedido"));
        jPanel5.setLayout(null);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 20, 400, 80);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 360, 420, 110);

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Calcular");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(458, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void modHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modHPActionPerformed
       
        jLabel5.setIcon(new ImageIcon(getClass().getResource("imagens/" + evt.getActionCommand() + ".jpg")));
        
    }//GEN-LAST:event_modHPActionPerformed

    private void modDELLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modDELLActionPerformed

        jLabel5.setIcon(new ImageIcon(getClass().getResource("imagens/" + evt.getActionCommand() + ".jpg")));

    }//GEN-LAST:event_modDELLActionPerformed

    private void modASUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modASUSActionPerformed

        jLabel5.setIcon(new ImageIcon(getClass().getResource("imagens/" + evt.getActionCommand() + ".jpg")));
        
    }//GEN-LAST:event_modASUSActionPerformed

    private void modSAMSUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modSAMSUNGActionPerformed

        jLabel5.setIcon(new ImageIcon(getClass().getResource("imagens/" + evt.getActionCommand() + ".jpg")));
        
    }//GEN-LAST:event_modSAMSUNGActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Sobre jan = new Sobre(this,true);
        jan.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        calcular();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jPanel5.setBackground(Color.pink);        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jPanel5.setBackground(Color.cyan);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    public void calcular(){
        
        if (jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Digite o nome do cliente");
            return;
        }
        //calcular e exibir
        float preco=0;
        
        //verifica modelo
        if (modHP.isSelected())
            preco = 2000;
        else if (modDELL.isSelected())
            preco = 1500;
        else if (modASUS.isSelected())
            preco = 1800;
        else if (modSAMSUNG.isSelected())
            preco = 2100;
        else{
            JOptionPane.showMessageDialog(null, "Selecione um modelo");
            return;
        }
        
        if (acMOUSE.isSelected())
            preco += 60;
	
        if (acIMP.isSelected())
            preco += 500;
        
        if (acMONITOR.isSelected())
            preco += 600;
	
        //frete
        if (regiao.getSelectedIndex() >=0 && regiao.getSelectedIndex() <= 2)
        {
            preco += 100;
        } else if (regiao.getSelectedIndex() < 0){
            JOptionPane.showMessageDialog(null, "Selecione o local de entrega");
            return;
        }
     
        
        String strpag="";
        if (boleto.isSelected()){
            preco = preco - (preco*0.10f);
            strpag = " (à vista)";
        }
        else if (cartao.isSelected()){
            preco = preco / 2;
            strpag = " (2 parcelas) ";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a forma de pagamento");
            return;
        }
        
	
        jLabel6.setText(jTextField1.getText() + ", o total do seu pedido é: " + strpag + "R$ " + preco);
        limparCampos();
    }
    
    public void limparCampos(){
        jTextField1.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        acIMP.setSelected(false);
        acMONITOR.setSelected(false);
        acMOUSE.setSelected(false);
        regiao.clearSelection();  
        //jLabel5.setIcon(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LojaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LojaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LojaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LojaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LojaInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acIMP;
    private javax.swing.JCheckBox acMONITOR;
    private javax.swing.JCheckBox acMOUSE;
    private javax.swing.JRadioButton boleto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton cartao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton modASUS;
    private javax.swing.JRadioButton modDELL;
    private javax.swing.JRadioButton modHP;
    private javax.swing.JRadioButton modSAMSUNG;
    private javax.swing.JList regiao;
    // End of variables declaration//GEN-END:variables
}
