/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Aluno;
import dao.AlunoDAO;
import java.util.List;
import javax.swing.JOptionPane;


public class CadAlunos extends javax.swing.JFrame {

    /**
     * Creates new form CadAlunos
     */
    public CadAlunos() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("RGM:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 60, 14);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 60, 14);

        jLabel3.setText("Curso: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 60, 14);

        jLabel4.setText("E-mail:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 60, 14);

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 150, 65, 23);

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 150, 65, 23);

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 150, 63, 23);

        jButton4.setText("Consultar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(210, 150, 90, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 400, 100);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 30, 360, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(60, 60, 360, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Análise e Desenv. de Sistemas", "Ciência da Computação", "Jogos Digitais", "Redes de Computadores" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(60, 90, 220, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(60, 120, 360, 20);

        jButton5.setText("Listar Todos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(310, 150, 110, 23);

        setBounds(0, 0, 452, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Aluno aluno = montaAluno();
        String resp = new AlunoDAO().gravarAluno(aluno);
        
        if(resp.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Aluno Gravado com sucesso");
            limparCampos();
        }
        else {
            jTextArea1.setText((resp));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Aluno aluno = new AlunoDAO().getAluno(jTextField1.getText());
        if (aluno != null){            
            exibeAluno(aluno);
        }
        else
        {
            jTextArea1.setText("Registro não encontrado.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:        
        if (new AlunoDAO().delAluno(jTextField1.getText())){            
            JOptionPane.showMessageDialog(null, "Registro excluído.");
            limparCampos();
        }
        else
        {
            jTextArea1.setText("Registro não encontrado.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Aluno aluno = montaAluno();
        String resp = new AlunoDAO().alterarAluno(aluno);
        
        if(resp.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Aluno alterado com sucesso");
            limparCampos();
        }
        else {
            jTextArea1.setText((resp));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        List<Aluno> alunos = new AlunoDAO().listarAlunos();
	int i = 0;
	jTextArea1.setText("");
        if (alunos.size()>0){
            while (i < alunos.size()) {
		Aluno a = alunos.get(i);
                jTextArea1.append("Aluno " + (i + 1) + "\n");
		jTextArea1.append("RGM: " + a.getRGM() + ", ");
		jTextArea1.append("Nome: " + a.getNome() + ", ");
		jTextArea1.append("Curso: " + a.getCurso() + ", ");
		jTextArea1.append("Email: " + a.getEmail() + "\n\n");		
		i++;
            }			
	}
	else
            JOptionPane.showMessageDialog(null,"Banco de dados vazio.");
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAlunos().setVisible(true);
            }
        });
    }
    
    public Aluno montaAluno(){
        Aluno aluno = new Aluno();
        aluno.setRGM(jTextField1.getText());
        aluno.setNome(jTextField2.getText());
        aluno.setCurso(jComboBox1.getSelectedItem().toString());
        aluno.setEmail(jTextField3.getText());
        return aluno;
    }

    public void exibeAluno(Aluno aluno){
        jTextField2.setText(aluno.getNome());
        jTextField3.setText(aluno.getEmail());
        jComboBox1.setSelectedItem(aluno.getCurso());
    }
    
    public void limparCampos(){
        jTextField1.setText("");
        jTextField2.setText("");
        jComboBox1.setSelectedIndex(0);
        jTextField3.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
