/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.*;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        carregarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jLabel1.setText("Referência:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(11, 12, 70, 14);

        jLabel2.setText("Marca:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 33, 14);

        jLabel3.setText("Modelo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 38, 14);

        jLabel4.setText("Ano:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 100, 23, 14);

        jLabel5.setText("Preço:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 100, 31, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(90, 10, 160, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(90, 70, 160, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(90, 100, 40, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(180, 100, 70, 20);

        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(90, 40, 160, 20);

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 50, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 550, 130);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 150, 90, 170);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Referência", "Marca", "Modelo", "Ano", "Preço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane3.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(110, 150, 450, 170);

        setSize(new java.awt.Dimension(581, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        int linha = jList1.getSelectedIndex();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();        
        List<Veiculo> lista = new VeiculoDAO().listarVeiculos(idMarca[linha]);
        
        modelo.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {            
            modelo.addRow(new String[]{ lista.get(i).getReferencia(),
                                        lista.get(i).getMarca()+"",
                                        lista.get(i).getModelo(),
                                        lista.get(i).getAno()+"",
                                        lista.get(i).getPreco()+""});
        }   
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Veiculo v = montaVeiculo();
        String resp = new VeiculoDAO().gravarVeiculo(v);
        
        if(resp.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Veículo Gravado com sucesso");            
        }
        else {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    public void carregarLista() {
        DefaultListModel listam = new DefaultListModel(); 
        List<Marca> lista = new MarcaDAO().listarMarcas();
        idMarca = new int[lista.size()];
        for (int i = 0; i < lista.size(); i++) {
            jComboBox1.addItem(lista.get(i).getMarca());
            listam.addElement(lista.get(i).getMarca());
            idMarca[i] = lista.get(i).getId();
        }  
        jList1.setModel(listam);
    }
    
    public Veiculo montaVeiculo(){
        Veiculo v = new Veiculo();
        v.setReferencia(jTextField1.getText());
        v.setMarca(idMarca[jComboBox1.getSelectedIndex()]);
        v.setModelo(jTextField3.getText());
        v.setAno(Integer.parseInt(jTextField4.getText()));
        v.setPreco(Float.parseFloat(jTextField5.getText()));
        return v;
    }  
    
    int idMarca[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
