/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.*;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alcides
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        carregarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        jLabel6.setText("Código:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(11, 12, 70, 14);

        jLabel7.setText("Tipo:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 40, 24, 14);

        jLabel8.setText("Nome:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 70, 31, 14);

        jLabel9.setText("Preço: ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 100, 50, 14);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(90, 10, 160, 20);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(90, 70, 160, 20);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(90, 100, 100, 20);

        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(90, 40, 160, 20);

        jButton2.setText("Gravar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(310, 50, 80, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 510, 130);

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList2);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 150, 90, 170);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Tipo", "Nome", "Preço"
            }
        ));
        jScrollPane6.setViewportView(jTable2);

        jScrollPane5.setViewportView(jScrollPane6);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(110, 150, 410, 170);

        setBounds(0, 0, 546, 371);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu m = montaMenu();
        String resp = new MenuDAO().gravarMenu(m);
        
        if(resp.equals("OK")) {
            JOptionPane.showMessageDialog(null, "Menu Gravado com sucesso");            
        }
        else {
            JOptionPane.showMessageDialog(null, resp);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
         int linha = jList2.getSelectedIndex();
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();        
        List<Menu> lista = new MenuDAO().listarMenus(idTipo[linha]);
        
        modelo.setNumRows(0);
        for (int i = 0; i < lista.size(); i++) {            
            modelo.addRow(new String[]{ lista.get(i).getCodigo()+"",
                                        lista.get(i).getTipo(),
                                        lista.get(i).getNome(),                                       
                                        lista.get(i).getPreco()+""});
        }   
    }//GEN-LAST:event_jList2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }
    
    public void carregarLista() {
        DefaultListModel listat = new DefaultListModel(); 
        List<TipoOferta> lista = new TipoOfertaDAO().listarTipos();
        idTipo = new String[lista.size()];
        for (int i = 0; i < lista.size(); i++) {
            jComboBox2.addItem(lista.get(i).getDescricao());
            listat.addElement(lista.get(i).getDescricao());
            idTipo[i] = lista.get(i).getTipo();
        }  
        jList2.setModel(listat);
    }
    
    
    public Menu montaMenu(){
        Menu m = new Menu();
        m.setCodigo(Integer.parseInt(jTextField2.getText()));
        m.setTipo(idTipo[jComboBox2.getSelectedIndex()]);
        m.setNome(jTextField6.getText());
        m.setPreco(Float.parseFloat(jTextField7.getText()));
        return m;
    }   
    
    
    
    String idTipo[];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
