
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * RGM: 1212121
 * NOME: Fulano da Silva
 * Curso: TADS
 */
public class LojaCarros extends javax.swing.JFrame {

    /**
     * Creates new form LojaInfo
     */
    public LojaCarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buggati = new javax.swing.JRadioButton();
        lamborghini = new javax.swing.JRadioButton();
        ferrari = new javax.swing.JRadioButton();
        acNITRO = new javax.swing.JCheckBox();
        acINSULFIM = new javax.swing.JCheckBox();
        acGPS = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cidade = new javax.swing.JList();
        parcelas = new javax.swing.JRadioButton();
        avista = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do cliente"));
        jPanel1.setLayout(null);

        jLabel1.setText("Nome do cliente:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 100, 14);

        jLabel2.setText("Est civil:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 44, 50, 14);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Casado");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(140, 40, 61, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Solteiro");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(60, 40, 80, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(90, 15, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 230, 70);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Loja de Carros Importados");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 20, 440, 26);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Selecione um veículo/acessórios"));
        jPanel2.setLayout(null);

        buttonGroup3.add(buggati);
        buggati.setText("Buggati");
        buggati.setOpaque(false);
        buggati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buggatiActionPerformed(evt);
            }
        });
        jPanel2.add(buggati);
        buggati.setBounds(10, 20, 90, 23);

        buttonGroup3.add(lamborghini);
        lamborghini.setText("Lamborghini");
        lamborghini.setOpaque(false);
        lamborghini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamborghiniActionPerformed(evt);
            }
        });
        jPanel2.add(lamborghini);
        lamborghini.setBounds(10, 40, 110, 23);

        buttonGroup3.add(ferrari);
        ferrari.setText("Ferrari");
        ferrari.setOpaque(false);
        ferrari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ferrariActionPerformed(evt);
            }
        });
        jPanel2.add(ferrari);
        ferrari.setBounds(10, 60, 90, 23);

        acNITRO.setText("Nitro");
        jPanel2.add(acNITRO);
        acNITRO.setBounds(130, 20, 49, 23);

        acINSULFIM.setText("Insulfilm");
        jPanel2.add(acINSULFIM);
        acINSULFIM.setBounds(130, 40, 65, 23);

        acGPS.setText("GPS");
        jPanel2.add(acGPS);
        acGPS.setBounds(130, 60, 45, 23);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 90, 210, 200);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, 60, 230, 330);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Local de entrega e dados de pagamento"));
        jPanel4.setLayout(null);

        jLabel4.setText("Cidade:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 20, 70, 14);

        cidade.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Ceará", "Rio de Janeiro", "Santa Catarina", "São Paulo", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        cidade.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(cidade);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 130, 50);

        buttonGroup2.add(parcelas);
        parcelas.setText("4 Parcelas");
        parcelas.setOpaque(false);
        jPanel4.add(parcelas);
        parcelas.setBounds(20, 110, 90, 23);

        buttonGroup2.add(avista);
        avista.setText("Á vista");
        avista.setOpaque(false);
        jPanel4.add(avista);
        avista.setBounds(20, 90, 93, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 130, 230, 140);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Relatório do pedido"));
        jPanel5.setLayout(null);

        jScrollPane2.setOpaque(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 210, 90);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 270, 230, 120);

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Calcular");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(496, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buggatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buggatiActionPerformed
       
        jLabel5.setIcon(new ImageIcon(getClass().getResource("figuras/" + evt.getActionCommand() + ".jpg")));
        
    }//GEN-LAST:event_buggatiActionPerformed

    private void lamborghiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamborghiniActionPerformed

        jLabel5.setIcon(new ImageIcon(getClass().getResource("figuras/" + evt.getActionCommand() + ".jpg")));

    }//GEN-LAST:event_lamborghiniActionPerformed

    private void ferrariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ferrariActionPerformed

        jLabel5.setIcon(new ImageIcon(getClass().getResource("figuras/" + evt.getActionCommand() + ".jpg")));
        
    }//GEN-LAST:event_ferrariActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Sobre jan = new Sobre(this,true);
        jan.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        calcular();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:       
        acNITRO.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:        
        acNITRO.setSelected(false);
        acNITRO.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    public void calcular(){
        
        if (jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Digite o nome do cliente");
            return;
        }
        //calcular e exibir 	
        float preco=0;
        
        //verifica modelo
        if (buggati.isSelected())
            preco = 2000000;
        else if (lamborghini.isSelected())
            preco = 1000000;
        else if (ferrari.isSelected())
            preco = 1200000;        
        else{
            JOptionPane.showMessageDialog(null, "Selecione um veículo");
            return;
        }
        
        if (acNITRO.isSelected())
            preco += 1500;
	
        if (acINSULFIM.isSelected())
            preco += 500;
        
        if (acGPS.isSelected())
            preco += 200;
	
        //frete
        if (cidade.getSelectedIndex() < 0)
        {
            JOptionPane.showMessageDialog(null, "Selecione o local de entrega");
            return;
        } else if (cidade.getSelectedValue().equals("São Paulo") || cidade.getSelectedValue().equals("Rio de Janeiro"))
        {
            preco += 5000;
        } else {
            preco += 10000;
        }
     
        
        String strpag="";
        if (avista.isSelected()){
            preco = preco - (preco*0.15f);
            strpag = " (à vista)";
        }
        else if (parcelas.isSelected()){
            preco = preco / 4;
            strpag = " (4 parcelas) ";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a forma de pagamento");
            return;
        }
        
	
        jTextArea1.setText(jTextField1.getText() + ", o total do seu pedido é: " + strpag + "R$ " + preco);
        limparCampos();
    }
    
    public void limparCampos(){
        jTextField1.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        acINSULFIM.setSelected(false);
        acGPS.setSelected(false);
        acNITRO.setSelected(false);
        cidade.clearSelection();  
        //jLabel5.setIcon(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LojaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LojaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LojaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LojaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LojaCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acGPS;
    private javax.swing.JCheckBox acINSULFIM;
    private javax.swing.JCheckBox acNITRO;
    private javax.swing.JRadioButton avista;
    private javax.swing.JRadioButton buggati;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JList cidade;
    private javax.swing.JRadioButton ferrari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton lamborghini;
    private javax.swing.JRadioButton parcelas;
    // End of variables declaration//GEN-END:variables
}
